[package]
name = "sometime-core"
version = "0.1.0"
edition = "2024"

[dependencies]
smithay-client-toolkit = { workspace = true }
wayland-client = { workspace = true }
chrono = { workspace = true }
env_logger = { workspace = true }
