[package]
name = "sometime"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = { version = "0.4.43", features = ["serde"] }
cosmic-text = "0.16.0"
libc = "0.2.180"
smithay-client-toolkit = "0.20.0"
wayland-client = "0.31.12"
