[package]
name = "sometime-clock"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sometime-clock"
path = "src/main.rs"

[dependencies]
sometime-core = { path = "../sometime-core" }
chrono = { workspace = true }
smithay-client-toolkit = { workspace = true }
wayland-client = { workspace = true }
