[package]
name = "sometime-clock"
version = "25.12.28"
edition = "2024"

[[bin]]
name = "sometime-clock"
path = "src/main.rs"

[dependencies]
sometime = { path = "../sometime" }
chrono = { workspace = true }
smithay-client-toolkit = { workspace = true }
wayland-client = { workspace = true }
