[package]
name = "sometime"
version = "25.12.28"
edition = "2024"

[dependencies]
smithay-client-toolkit = { workspace = true }
wayland-client = { workspace = true }
chrono = { workspace = true }
env_logger = { workspace = true }
